name: Semgrep

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**.go'
      - '.semgrep/**'

jobs:
  semgrep:
    name: Code Quality Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:1.110.0
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Fix Git Ownership
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Run Semgrep (PR diff only)
        run: |
          git fetch origin ${{ github.base_ref }}
          BASE_COMMIT=$(git rev-parse origin/${{ github.base_ref }})

          # Display results in human-readable format
          semgrep \
            --config .semgrep/ \
            --baseline-commit $BASE_COMMIT \
            .
