name: Semgrep

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**.go'
      - '.semgrep/**'

jobs:
  semgrep:
    name: Code Quality Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:1.110.0
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Run Semgrep on changed files only
        run: |
          git fetch origin ${{ github.base_ref }}
          
          semgrep \
            --config .semgrep/ \
            .
