name: Semgrep

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**.go'
      - '.semgrep/**'

jobs:
  semgrep:
    name: Code Quality Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:1.110.0
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2
      - name: Fix Git Ownership
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Run Semgrep (PR diff only)
        run: |
          semgrep \
            --config .semgrep/ \
            --baseline-commit HEAD^1 \
            --error \
            .
